### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 200
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "5b53d564524641388bcafe216cb11aae",
  "accountNumber": "1000000000",
  "amount": 3000
}

### get transaction
GET http://localhost:8080/transaction/17b212c6777d4d739e843f3293771f9b
